-- USER SQL
CREATE USER "JMTT_ECOMMERCE"

IDENTIBIED BY "XXX"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES
ALTER USER "JMTT_ECOMMERCE" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES

GRANT CREATE ANY VIEW TO "JMTT_ECOMMERCE" ;